#!/bin/bash
alias userGenerate="bash /home/tharun/Desktop/sysad1/1.usergenerate"
alias permit="bash /home/tharun/Desktop/sysad1/2.permit"
alias autoSchedule="bash /home/tharun/Desktop/sysad1/3.autoschedule"
alias attendance="bash /home/tharun/Desktop/sysad1/4.attendance"
alias record="bash /home/tharun/Desktop/sysad1/5.record"
alias finalattendance="bash /home/tharun/Desktop/sysad1/hackermode1.finalattendance"
alias nearest="bash /home/tharun/Desktop/sysad1/hackermode2.nearest10"
